### ISSUE TITLE
Debug-2d feature makes scales not work

### ISSUE THREAD

**Issue by edgarssilva** [jcornaz/heron#136] opened 2021-08-18 10:59 UTC
When I enable the `debug-2d` feature transform scales seem to stop working, also I have a little system to zoom in and out the camera that also stops working. With this it becomes a bit hard to debug because the size of the debugs don't match the sprite.

**Comment by jcornaz** [comment] 2021-08-18 11:46
The collision shapes ignores the scale. The debug shapes should also ignore the scale to be a correct representation of the actual rapier collision shape.

But it shouldn't have more impact than that. I'm surprised that it mess-up *other* things, such as the camera. Do you mind sharing a code example?

**Comment by edgarssilva** [comment] 2021-08-18 12:06
It's quite a bit of code and in alot of places but I'll try to show the important bits.

This is a simple enemy it has a scale of 0.5.
```rust
//Add enemy
    commands
        .spawn()
        .insert_bundle(SpriteBundle {
            material: materials.add(asset_server.load("old/char/iddle_l1.png").into()),
            transform: Transform {
                translation: Vec3::new(30., 5., PLAYER_Z),
                scale: Vec3::splat(0.5),
                ..Default::default()
            },
            ..Default::default()
        })
        .insert(RigidBody::KinematicPositionBased)
        .insert(CollisionShape::Cuboid {
            half_extends: Vec3::new(4.0, 8.0, 0.),
            border_radius: None,
        });
```
I also tried to make the scale 5 and for like the first second it shows a huge sprite but then scales down to 1. (Also have other sprites with the same behaviour).

```rust
let mut camera_bundle = OrthographicCameraBundle::new_2d();
camera_bundle.orthographic_projection.scale = 0.15;
```
This is the camera initial scale works just fine but if I try to update it doesn't work (works without the debug).

**Comment by jcornaz** [comment] 2021-08-18 12:18
ok. Thanks. I'll see if I can reproduce it with this code.

But just to be clear the collision shape (and it's debug rendering) is _not_ supposed to follow the scale. And because the sprite will follow the scale, it is expected that the sprite and collision shape won't match, unless the collision shape dimension is changed.

**Comment by edgarssilva** [comment] 2021-08-18 12:24
Yeah that was the behaviour I was expecting but it's hard visualise if the dimensions are correct with the sprite always having the scale to 1.

**Comment by edgarssilva** [comment] 2021-08-20 14:15
I think this problem is in https://github.com/jcornaz/heron/blob/8c2998fe5e2679f1b404cade9221ff5ba7fd8799/debug/src/lib.rs#L81

**Comment by jcornaz** [comment] 2021-08-20 14:19
@edgarssilva that system intentionally make sure the rendered debug shape absolute scale is 1. So that it matches the actual collision shape which is not affected by scale.

**Comment by edgarssilva** [comment] 2021-08-20 14:40
I've created a fork for myself and commented line where the system is added. 
Seems to work in 2d and the sprites are no longer forced to have scale of 1.
It might have some implications in 3d so idk.

**Comment by jcornaz** [comment] 2021-08-20 14:47
Ah, I understand. The query of that system was too broad. @edgarssilva can you try with the content of the PR #138?

**Comment by edgarssilva** [comment] 2021-08-20 14:49
That was the fix I had in mind. You can close the issue or I'll close it myself once the pr is merched.

**Comment by jcornaz** [comment] 2021-08-20 14:52
@edgarssilva Merging the PR will automatically close this issue. Il publish the fix to crates.io fix tonight.

Thanks for the report and investiguations :-)

**Closed** 2021-08-20 15:01 UTC
