### ISSUE TITLE
Sensor affects velocity

### ISSUE THREAD

**Issue by stillonearth** [jcornaz/heron#287] opened 2022-07-08 11:37 UTC
An object would loose velocity colliding with sensor

**Comment by jcornaz** [comment] 2022-07-09 11:02
Are you reporting a bug, describing the current behavior? Or is it a feature request?

If it is a bug, please provide a reproducer. If it is a feature request, can you please explain your use-case?

**Comment by jcornaz** [comment] 2022-08-03 11:04
I am closing, due to lack of information.

@stillonearth, feel free to open another issue describing either:
 * Your use-case (if it is a feature request)
 * How to reproduce (if it is a bug)

**Closed by jcornaz** 2022-08-03 11:04 UTC

**Comment by stillonearth** [comment] 2022-08-04 04:52
It's not relevant anymore, but I'll try to reproduce on bevy 0.8 once new heron is released.
